### ISSUE TITLE
Utility Network Trace - "The input feature does not belong to this utility network."

### ISSUE THREAD

**Issue by philium** [Esri/arcgis-maps-sdk-swift-toolkit#227] opened 2022-12-19 21:05 UTC
When using the Utility Network Trace sample, I'm seeing the following error logged to the console:

```
error occurred: code: 2
error message: Invalid argument.
error additional message: The input feature does not belong to this utility network.
```

Steps to reproduce:

1. Open the Utility Network Trace example
2. Select Connected as the trace configuration
3. Tap/click Add New to add a starting point
4. Tap/click on a feature

**Comment by dfeinzimer** [comment] 2022-12-19 21:49
Hi @philium, for step 4, do you recall which feature you tapped on? I've tried a few and haven't gotten this messaging in the console.

**Comment by philium** [comment] 2022-12-19 21:57
Here you go:

https://user-images.githubusercontent.com/2257493/208531814-92d90b14-f795-4496-8e60-3eacf233ac9b.mov

There's also another error about "geometries must not be empty" when tapping Trace.

**Comment by dfeinzimer** [comment] 2022-12-28 18:27
The error seems to be coming out of core when calling `UtilityNetwork.makeElement(arcGISFeature:terminal:)`. I can reproduce the error when attempting to make an element with a feature with a subtype name of "Medium Voltage Radial". I don't see an obvious way to predetermine if a feature belongs to a utility network so [I've checked with the team](https://esri-runtime.slack.com/archives/CHV3XNY00/p1672252044547409).

**Comment by dfeinzimer** [comment] 2022-12-28 18:32
> There's also another error about "geometries must not be empty" when tapping Trace.

I'll be investigating this under #233 as it appears to be a separate issue.

**Comment by dfeinzimer** [comment] 2022-12-28 19:31
@philium As Ryan suggested in the linked thread, I experimented with using a `withErrorHandler`. That works and stops this from being logged but of course that may end up stopping other helpful messages. Do you have an opinion on whether we should proceed and stop the logging or close this without change? My thinking is that it's a valid error and we should continue to log it.

**Comment by rolson** [comment] 2022-12-28 19:33
Can you create an issue in our internal Swift API repo to discuss that?

**Comment by dfeinzimer** [comment] 2022-12-28 19:42
Ref Swift #3246

**Comment by dfeinzimer** [comment] 2023-03-02 22:57
Behavior may change as a result of Swift 3714

**Comment by dfeinzimer** [comment] 2023-03-04 01:16
Closing; as of Swift 3714 the error is discarded and no longer logged.

**Closed by dfeinzimer** 2023-03-04 01:16 UTC
Labels: bug
